In [1]:
import pandas as pd
import numpy as np

In [2]:
coffee = pd.read_csv('coffee_groc_1114_1165', delim_whitespace=True)

In [3]:
delivery = pd.read_csv('Delivery.csv')

In [4]:
time = pd.read_csv('IRI week translation.csv')

In [5]:
coffee.head(2)

   IRI_KEY  WEEK  SY  GE   VEND   ITEM  UNITS  DOLLARS     F    D   PR
0   253422  1114   0   1  43000  75305      1     6.99  NONE  0.0  0.0
1   253422  1114   0   1  43000  70170      2    13.98  NONE  0.0  0.0

In [6]:
delivery.head(2)

   IRI_KEY  OU    EST_ACV        Market_Name  Open  Clsd MskdName
0   200039  GR   9.709999  BUFFALO/ROCHESTER   539  1219  Chain87
1   200171  GR  27.690990          MILWAUKEE   522  9998  Chain97

In [7]:
delivery.isna().sum()

IRI_KEY        0
OU             0
EST_ACV        0
Market_Name    0
Open           0
Clsd           0
MskdName       0
dtype: int64

In [8]:
time.head(2)

,WEEK,Calendar week starting on,Calendar week ending on,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,1138,18-Jun-01,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1139,25-Jun-01,1-Jul-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
time.isna().sum()

WEEK                           0
Calendar week starting on      0
Calendar week ending on        0
Unnamed: 3                   526
Unnamed: 4                   526
Unnamed: 5                   526
Unnamed: 6                   526
Unnamed: 7                   526
Unnamed: 8                   526
Unnamed: 9                   526
Unnamed: 10                  526
Unnamed: 11                  525
dtype: int64

In [10]:
coffee.isna().sum()

IRI_KEY    0
WEEK       0
SY         0
GE         0
VEND       0
ITEM       0
UNITS      0
DOLLARS    1
F          1
D          1
PR         1
dtype: int64

In [11]:
coffee = coffee.dropna()

In [12]:
coffee.PR.unique()

array([0., 1.])

In [13]:
coffee.D.unique()

array([0., 1., 2.])

In [14]:
coffee.F.unique()

array(['NONE', 'B', 'A', 'A+', 'C'], dtype=object)

In [15]:
coffee.UNITS.unique()

array([   1,    2,    4, ..., 1448, 1925,  980])

In [16]:
coffee.GE.unique()

array([1, 2, 3, 4, 6, 5])

In [17]:
coffee.SY.unique()

array([ 0,  7, 88,  6,  8,  1, 26, 27])

In [18]:
coffee['VEND'].value_counts()

25500    1185527
43000    1082745
99998     717672
75101     493210
62111     437090
          ...
76238          1
36462          1
71194          1
67977          1
94581          1
Name: VEND, Length: 207, dtype: int64

In [19]:
coffee['ITEM'].value_counts()

70522    65843
80258    64945
80273    64092
81121    61219
51       56150
         ...
50540        1
15701        1
3068         1
45415        1
30780        1
Name: ITEM, Length: 2839, dtype: int64

In [20]:
coffee.head(2)

   IRI_KEY  WEEK  SY  GE   VEND   ITEM  UNITS  DOLLARS     F    D   PR
0   253422  1114   0   1  43000  75305      1     6.99  NONE  0.0  0.0
1   253422  1114   0   1  43000  70170      2    13.98  NONE  0.0  0.0

In [21]:
delivery.head(2)

   IRI_KEY  OU    EST_ACV        Market_Name  Open  Clsd MskdName
0   200039  GR   9.709999  BUFFALO/ROCHESTER   539  1219  Chain87
1   200171  GR  27.690990          MILWAUKEE   522  9998  Chain97

In [22]:
display("The merged DataFrame")
df= pd.merge(delivery, coffee , on = "IRI_KEY", how = "inner")

'The merged DataFrame'

In [23]:
df.head(2)

,IRI_KEY,OU,EST_ACV,Market_Name,Open,Clsd,MskdName,WEEK,SY,GE,VEND,ITEM,UNITS,DOLLARS,F,D,PR
0,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1114,0,1,43000,75105,5,12.45,NONE,0.0,1.0
1,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1114,0,1,43000,75305,5,29.95,NONE,0.0,1.0

In [24]:
df= pd.merge(df, time , on = "WEEK", how = "inner")
df.head(10)

,IRI_KEY,OU,EST_ACV,Market_Name,Open,Clsd,MskdName,WEEK,SY,GE,...,Calendar week ending on,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,3,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,2,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,2,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,...,24-Jun-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df= df.drop(['Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11'], axis = 1)

In [26]:
df.head(2)

,IRI_KEY,OU,EST_ACV,Market_Name,Open,Clsd,MskdName,WEEK,SY,GE,VEND,ITEM,UNITS,DOLLARS,F,D,PR,Calendar week starting on,Calendar week ending on
0,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,1,43000,75105,16,40.0,A,0.0,1.0,18-Jun-01,24-Jun-01
1,200039,GR,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,1138,0,3,43000,70150,11,27.5,A,0.0,1.0,18-Jun-01,24-Jun-01

In [27]:
df.isna().sum()

IRI_KEY                      0
OU                           0
EST_ACV                      0
Market_Name                  0
Open                         0
Clsd                         0
MskdName                     0
WEEK                         0
SY                           0
GE                           0
VEND                         0
ITEM                         0
UNITS                        0
DOLLARS                      0
F                            0
D                            0
PR                           0
Calendar week starting on    0
Calendar week ending on      0
dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3203604 entries, 0 to 3203603
Data columns (total 19 columns):
 #   Column                     Dtype
---  ------                     -----
 0   IRI_KEY                    int64
 1   OU                         object
 2   EST_ACV                    float64
 3   Market_Name                object
 4   Open                       int64
 5   Clsd                       int64
 6   MskdName                   object
 7   WEEK                       int64
 8   SY                         int64
 9   GE                         int64
 10  VEND                       int64
 11  ITEM                       int64
 12  UNITS                      int64
 13  DOLLARS                    float64
 14  F                          object
 15  D                          float64
 16  PR                         float64
 17  Calendar week starting on  object
 18  Calendar week ending on    object
dtypes: float64(4), int64(9), object(6)
memory usage: 488.8+ MB

In [ ]:
df.['SY'] = "% s" % a

In [76]:
df["UPC"] = df["SY"] + df["GE"] + df['VEND'] + df['ITEM']

In [77]:
#df= df.drop(['WEEK','SY','GE','OU','Calendar week ending on'], axis=1)
df= df.drop(['WEEK','OU','Calendar week ending on'], axis=1)

In [78]:
df = df.rename(columns = {'Calendar week starting on':'WEEK'})

In [79]:
df.head(2)

,IRI_KEY,EST_ACV,Market_Name,Open,Clsd,MskdName,SY,GE,VEND,ITEM,UNITS,DOLLARS,F,D,PR,WEEK,UPC
0,200039,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,0,1,43000,75105,16,40.0,A,0.0,1.0,18-Jun-01,118106
1,200039,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,0,3,43000,70150,11,27.5,A,0.0,1.0,18-Jun-01,113153

In [83]:
# Weekly Dollar sales by Store
#weekly_sales = df.drop(['VEND','PR','F','D','ITEM','Open', 'Clsd'], axis = 1)
weekly_sales = df.drop(['VEND','PR','F','D','ITEM','Open', 'Clsd','SY','GE'], axis = 1)
weekly_sales.head(4)

,IRI_KEY,EST_ACV,Market_Name,MskdName,UNITS,DOLLARS,WEEK,UPC
0,200039,9.709999,BUFFALO/ROCHESTER,Chain87,16,40.00,18-Jun-01,118106
1,200039,9.709999,BUFFALO/ROCHESTER,Chain87,11,27.50,18-Jun-01,113153
2,200039,9.709999,BUFFALO/ROCHESTER,Chain87,6,15.00,18-Jun-01,113911
3,200039,9.709999,BUFFALO/ROCHESTER,Chain87,3,23.97,18-Jun-01,113523

In [84]:
weekly_sales = weekly_sales.groupby(['IRI_KEY', 'WEEK']).sum()

In [85]:
weekly_sales.head(2)

                      EST_ACV  UNITS  DOLLARS      UPC
IRI_KEY WEEK
200039  1-Oct-01   737.959924    255  1085.75  6933452
        10-Dec-01  669.989931    267  1056.81  6108967

In [35]:
Store_sales = df.groupby(['IRI_KEY']).sum()
Store_sales.head(2)

,EST_ACV,Open,Clsd,SY,GE,VEND,ITEM,UNITS,DOLLARS,D,PR,UPC
IRI_KEY,,,,,,,,,,,,
200039,18206.248125,1010625,2285625,17259,2982,90733375,77071599,9628,33734.06,50.0,619.0,167825215
200171,137458.074360,2591208,49630072,18762,6202,229142184,131356028,38103,131870.79,82.0,1070.0,360523176

In [37]:
df.to_csv (r'\Desktop\merged.csv', index = False, header=True)

In [86]:
df_weekly = df.groupby(['IRI_KEY', 'WEEK'])['EST_ACV','UNITS','DOLLARS'].sum()
df_weekly.head(6)

<ipython-input-86-fe3b41bb64a8>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_weekly = df.groupby(['IRI_KEY', 'WEEK'])['EST_ACV','UNITS','DOLLARS'].sum()

                      EST_ACV  UNITS  DOLLARS
IRI_KEY WEEK
200039  1-Oct-01   737.959924    255  1085.75
        10-Dec-01  669.989931    267  1056.81
        10-Sep-01  660.279932    272   974.49
        12-Nov-01  689.409929    576  2185.97
        13-Aug-01  504.919948    190   761.63
        15-Oct-01  650.569933    269   905.21

In [87]:
df.head(3)

,IRI_KEY,EST_ACV,Market_Name,Open,Clsd,MskdName,SY,GE,VEND,ITEM,UNITS,DOLLARS,F,D,PR,WEEK,UPC
0,200039,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,0,1,43000,75105,16,40.0,A,0.0,1.0,18-Jun-01,118106
1,200039,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,0,3,43000,70150,11,27.5,A,0.0,1.0,18-Jun-01,113153
2,200039,9.709999,BUFFALO/ROCHESTER,539,1219,Chain87,0,1,43000,70910,6,15.0,A,0.0,1.0,18-Jun-01,113911

In [89]:
store_open = df['Clsd'] - df['Open']
store_open

0           680
1           680
2           680
3           680
4           680
           ...
3203599    8879
3203600    8879
3203601    8879
3203602    8879
3203603    8879
Length: 3203604, dtype: int64

In [101]:
df = df.drop(['MskdName'], axis =1)

KeyError: "['MskdName'] not found in axis"

In [101]:
feature = df.groupby(['F', 'ITEM'])['EST_ACV','UNITS','DOLLARS'].sum()
feature.head(2)

<ipython-input-101-3c78e0375386>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  feature = df.groupby(['F', 'ITEM'])['EST_ACV','UNITS','DOLLARS'].sum()

             EST_ACV   UNITS    DOLLARS
F ITEM
A 1     18808.138835  135227  214053.44
  3      3888.317679   16397   66057.84

In [105]:
feature.to_csv (r'feature.csv', index = True , header= False)

In [100]:
feature.shape

(4734, 3)

In [77]:
products = pd.read_csv('prod_coffee.csv')

In [78]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6929 entries, 0 to 6928
Data columns (total 21 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   L1                                                                                6929 non-null   object
 1   L2                                                                                6929 non-null   object
 2   L3                                                                                6929 non-null   object
 3   L4                                                                                6929 non-null   object
 4   L5                                                                                6929 non-null   object
 5   L9                                                                                6929 non-null   object
 6   Level                                                                             6929 non-null   int64
 7   UPC                                                                               6929 non-null   object
 8   SY                                                                                6929 non-null   int64
 9   GE                                                                                6929 non-null   int64
 10  VEND                                                                              6929 non-null   int64
 11  ITEM                                                                              6929 non-null   int64
 12  *STUBSPEC 1440RC                                                         00004    6929 non-null   object
 13  VOL_EQ                                                                            6929 non-null   float64
 14  PRODUCT TYPE                                                                      6929 non-null   object
 15  FLAVOR/SCENT                                                                      6929 non-null   object
 16  FORM                                                                              6929 non-null   object
 17  PACKAGE                                                                           6929 non-null   object
 18  BREWING METHOD                                                                    6928 non-null   object
 19  FAT CONTENT                                                                       6926 non-null   object
 20  FORM.1                                                                            6929 non-null   object
dtypes: float64(1), int64(5), object(15)
memory usage: 1.1+ MB

In [80]:
products['L5'].value_counts()['STARBUCKS']

151

In [81]:
flavours = products.groupby(['L5','FLAVOR/SCENT'])

In [82]:
flavours= products.loc[products['L5'] == 'STARBUCKS', 'FLAVOR/SCENT']
flavours

187          MISSING
188          MISSING
189          MISSING
190         ASSORTED
191         ASSORTED
            ...
4454    WINTER BLEND
4455    WINTER BLEND
4456    WINTER BLEND
4457         MISSING
4458         MISSING
Name: FLAVOR/SCENT, Length: 151, dtype: object

In [83]:
flavours.describe()

count         151
unique         26
top       MISSING
freq           42
Name: FLAVOR/SCENT, dtype: object

In [85]:
flavours.value_counts()

MISSING               42
HOUSE BLEND           24
FRENCH ROAST          12
BREAKFAST BLEND       11
CHRISTMAS BLEND       10
SUMATRA                7
COLOMBIAN              6
ESPRESSO ROAST         6
REGULAR                5
ASSORTED               4
WINTER BLEND           3
ITALIAN ROAST          3
ESPRESSO               2
VERONA                 2
CAFE VERONA            2
GAZEBO BLEND           2
MOCHA                  1
BLEND                  1
COLUMBIAN SUPREME      1
ETHIOPIA SIDAMO        1
PEABERRY               1
CHOCOLATE ESPRESSO     1
SPECIAL BLEND          1
TANZANIA               1
VIENNESE BLEND         1
SEASONAL BLEND         1
Name: FLAVOR/SCENT, dtype: int64

In [95]:
flavours = flavours[flavours != 'MISSING']

In [96]:
flavours.value_counts()

HOUSE BLEND           24
FRENCH ROAST          12
BREAKFAST BLEND       11
CHRISTMAS BLEND       10
SUMATRA                7
COLOMBIAN              6
ESPRESSO ROAST         6
REGULAR                5
ASSORTED               4
WINTER BLEND           3
ITALIAN ROAST          3
ESPRESSO               2
VERONA                 2
CAFE VERONA            2
GAZEBO BLEND           2
MOCHA                  1
BLEND                  1
COLUMBIAN SUPREME      1
ETHIOPIA SIDAMO        1
PEABERRY               1
CHOCOLATE ESPRESSO     1
SPECIAL BLEND          1
TANZANIA               1
VIENNESE BLEND         1
SEASONAL BLEND         1
Name: FLAVOR/SCENT, dtype: int64

In [97]:
flavours.to_csv (r'flavours.csv', index = False, header=True)

AttributeError: 'Series' object has no attribute 'to_xlxs'